name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Build exetuable (debug mode)
      run: cargo build --verbose
    - name: Build exetuable (release mode)
      run: cargo build --release --verbose
    - name: Upload Debug Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: web-voyager-judger-debug
        path: ./target/debug/web-voyager-judger
    - name: Upload Release Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: web-voyager-judger-release
        path: ./target/release/web-voyager-judger
